#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
#
# Build + zip the Osaurus plugin distribution package.
#
# Output: dist/dev.nivdvir.GroundingKit-0.1.0.zip
#
# Contents (per Osaurus PLUGIN_AUTHORING.md install layout):
#   libgroundingkit-osaurus.dylib
#   mlx-swift_Cmlx.bundle/                 ← Metal kernels (REQUIRED for MLX runtime)
#   SKILL.md                               ← agentskills.io frontmatter (loaded by Osaurus)
#   README.md
#   LICENSE
#
# IMPORTANT: the metallib bundle is NOT generated by `swift build` — mlx-swift's
# Cmlx target relies on Xcode's Metal compiler phase. We source the bundle from
# a pre-existing Xcode build of the same MLX dependency (GhostOverlay.app or
# any other MLX-linked .app). If you don't have one, see README → "Building
# from source — metallib".

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${ROOT}"

# Read plugin id + version from osaurus-plugin.json (single source of truth)
PLUGIN_ID=$(jq -r '.plugin_id' osaurus-plugin.json)
VERSION=$(jq -r '.version' osaurus-plugin.json)
ZIP_NAME="${PLUGIN_ID}-${VERSION}.zip"

echo "═══ Building ${PLUGIN_ID} v${VERSION} ═══"

# 1. Build the dylib
echo "→ swift build -c release"
swift build -c release

DYLIB_PATH=".build/release/libgroundingkit-osaurus.dylib"
if [[ ! -f "${DYLIB_PATH}" ]]; then
    echo "ERROR: dylib not found at ${DYLIB_PATH}"
    exit 1
fi

# 2. Verify entry symbol is exported
echo "→ verifying osaurus_plugin_entry symbol"
if ! nm -gU "${DYLIB_PATH}" | grep -q "_osaurus_plugin_entry"; then
    echo "ERROR: _osaurus_plugin_entry symbol missing from dylib"
    exit 1
fi

# 3. Locate metallib bundle (sourced from a sibling Xcode-built .app)
METALLIB_BUNDLE=""
for candidate in \
    "${HOME}/dev/GhostOverlay/GhostOverlay.app/Contents/Resources/mlx-swift_Cmlx.bundle" \
    ".build/release/mlx-swift_Cmlx.bundle"
do
    if [[ -d "${candidate}" ]]; then
        METALLIB_BUNDLE="${candidate}"
        break
    fi
done
if [[ -z "${METALLIB_BUNDLE}" ]]; then
    echo "ERROR: mlx-swift_Cmlx.bundle not found — see README → 'Building from source — metallib'"
    exit 1
fi
echo "→ metallib bundle: ${METALLIB_BUNDLE}"

# 4. Stage the package
STAGE="dist/${PLUGIN_ID}-${VERSION}"
rm -rf "${STAGE}" "dist/${ZIP_NAME}"
mkdir -p "${STAGE}"

cp "${DYLIB_PATH}"  "${STAGE}/"
cp -R "${METALLIB_BUNDLE}" "${STAGE}/"
cp SKILL.md README.md LICENSE osaurus-plugin.json "${STAGE}/"

# 5. Zip
echo "→ zipping → dist/${ZIP_NAME}"
( cd dist && zip -qr "${ZIP_NAME}" "${PLUGIN_ID}-${VERSION}" )

# 6. Report
SIZE=$(du -h "dist/${ZIP_NAME}" | cut -f1)
echo ""
echo "✓ Built dist/${ZIP_NAME} (${SIZE})"
echo ""
echo "Local install:"
echo "  mkdir -p ~/.osaurus/Tools/${PLUGIN_ID}/${VERSION}"
echo "  unzip -o dist/${ZIP_NAME} -d ~/.osaurus/Tools/"
